####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Service

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  name: {{ if and (hasKey .Values "service") (hasKey .Values.service "name") }}
            {{ .Values.service.name }}
         {{ else }}
            {{ .Values.meta.name }}
         {{ end }}
  labels:
    application: "{{ .Values.meta.name }}"

##################################
# Complete Service Specification #
##################################

spec:

  ###############################
  # Pod Selection Configuration #
  ###############################

  selector:
    application: "{{ .Values.meta.name }}"

  ##############################
  # Service Port Configuration #
  ##############################

  ports:

    - name: http
      port: {{ .Values.ports.http }}
      targetPort: 8080

    - name: https
      port: {{ .Values.ports.https }}
      targetPort: 8443