####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Service

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Values.configurationService.meta.name }}"
  labels:
    application: "{{ .Values.configurationService.meta.name }}"

##################################
# Complete Service Specification #
##################################

spec:

  ###############################
  # Pod Selection Configuration #
  ###############################

  selector:
    application: "{{ .Values.configurationDeployment.meta.name }}"

  ##############################
  # Service Port Configuration #
  ##############################

  ports:

    - name: default
      port: {{ .Values.configurationService.ports.default }}
      targetPort: 8888
