# This serves as a set of sensible defaults for authorization and query federation.
datawave:
  authorization:
    federation:
      # Each entry in the following map will be registered as a FederatedAuthorizationService bean, named after the key
      services:
        FederatedAuthorizationService:
          federatedAuthorizationUri: "https://{{ .Values.global.serviceDns.authorization.name }}:{{ .Values.global.serviceDns.authorization.port }}/{{ .Values.global.serviceDns.authorization.endpoint }}"
  query:
    federation:
      # Each entry in the following map will be registered as a FederatedQueryService (RemoteQueryService) bean, named after the key
      services:
        FederatedQueryService:
          queryServiceUri: 'https://{{ .Values.global.serviceDns.query.name }}:{{ .Values.global.serviceDns.query.port  }}/query/v1'
          queryMetricServiceUri: 'https://{{ .Values.global.serviceDns.metrics.name }}:{{ .Values.global.serviceDns.metrics.port }}/querymetric/v1/id'
