audit:
  confirmAckEnabled: false
  replay:
    enabled: true
  auditors:
    dump:
      enabled: false
      pathUri: file:///audit
    accumulo:
      enabled: true
      accumuloConfig:
          zookeepers: '${accumulo.zookeepers}'
          instanceName: '${accumulo.instanceName}'
          username: '${accumulo.username}'
          password: '${accumulo.password}'
    file:
      enabled: false
      maxFileAgeSeconds: 60
      maxLengthFileMB: 1
      pathUri: file:///audit
    log:
      enabled: true
logging:
  level:
    datawave.microservice.audit: DEBUG
spring:
  cloud:
    stream:
      bindings:
        accumuloAuditSink:
          destination: audit
          group: accumulo
        auditSource:
          destination: audit
        logAuditSink:
          destination: audit
          group: log
      rabbit:
        bindings:
          accumuloAuditSink:
            consumer:
              autoBindDlq: true
          auditSource:
            producer:
              repbulishToDlq: true
          logAuditSink:
            consumer:
              autoBindDlq: true