audit:
  auditors:
    accumulo:
      enabled: false
    file:
      enabled: false
      maxFileAgeSeconds: 60
      maxLengthFileMB: 1
      pathUri: s3a://signus-audits/
    log:
      enabled: false
logging:
  level:
    datawave.microservice.audit: DEBUG
spring:
  cloud:
    stream:
      bindings:
        accumuloAuditSink:
          destination: audit
          group: accumulo
        auditSource:
          destination: audit
        logAuditSink:
          destination: audit
          group: log
      rabbit:
        bindings:
          accumuloAuditSink:
            consumer:
              autoBindDlq: true
          auditSource:
            producer:
              repbulishToDlq: true
          logAuditSink:
            consumer:
              autoBindDlq: true