audit:
  confirmAckEnabled: false
  auditors:
    accumulo:
      enabled: false
    file:
      enabled: false
      maxFileAgeSeconds: 60
      maxLengthFileMB: 1
      pathUri: s3a://signus-audits/
    log:
      enabled: false
logging:
  level:
    datawave.microservice.audit: DEBUG