audit:
  auditors:
    accumulo:
      enabled: {{ .Values.audit.accumulo.enabled }}
      tableName: '{{ .Values.audit.accumulo.tableName }}'
      accumuloConfig:
        zookeepers: '{{ .Values.global.zookeeper.quorum }}'
        instanceName: '{{ .Values.global.accumulo.instanceName }}'
        username: '{{ .Values.global.accumulo.user }}'
        password: '{{ .Values.global.accumulo.password }}'
    file:
      enabled: false
      maxFileAgeSeconds: 60
      maxLengthFileMB: 1
      pathUri: s3a://signus-audits/
    log:
      enabled: false
logging:
  level:
    datawave.microservice.audit: DEBUG
spring:
  cloud:
    stream:
      bindings:
        accumuloAuditSink-in-0:
          destination: audit
          group: accumulo
        auditSource-out-0:
          destination: audit
          producer:
            errorChannelEnabled: true
        logAuditSink-in-0:
          destination: audit
          group: log
      rabbit:
        bindings:
          accumuloAuditSink-in-0:
            consumer:
              autoBindDlq: true
          logAuditSink-in-0:
            consumer:
              autoBindDlq: true
    function:
      definition: auditSource;accumuloAuditSink;busConsumer
