datawave:
  dictionary:
    accumulo-properties:
      instance-name: "{{ .Values.global.accumulo.instanceName }}"
      password: "{{ .Values.global.accumulo.password }}"
      username: "{{ .Values.global.accumulo.user }}"
      zookeepers: "{{ .Values.global.zookeeper.quorum }}"
    edge:
      metadata-table-name: ${metadata.tabl.name:datawave.metadata}
      num-threads: 8
    data:
      model-name: DATAWAVE
      metadata-table-name: ${metadata.table.name:datawave.metadata}
      model-table-name: ${metadata.table.name:datawave.metadata}
      normalizer-map:
        "[datawave.data.type.GeoLatType]": "Latitude"
        "[datawave.data.type.GeoLonType]": "Longitude"
        "[datawave.data.type.GeometryType]": "Geometry (WKT)"
        "[datawave.data.type.GeoType]": "Combined latitude, longitude"
        "[datawave.data.type.IpAddressType]": "IP address"
        "[datawave.data.type.MacAddressType]": "MAC address"
        "[datawave.data.type.LcNoDiacriticsType]": "Text"
        "[datawave.data.type.LcType]": "Text"
        "[datawave.data.type.NoOpType]": "Unnormalized Text"
        "[datawave.data.type.NumberType]": "Number"
        "[datawave.data.type.PointType]": "Point Geometry (WKT)"
        "[datawave.data.type.TrimLeadingZerosType]": "Text"
      num-threads: 8
  metadata:
    all-metadata-auths:
      - PUBLIC
    type-substitutions:
      "[datawave.data.type.DataType]": "datawave.data.type.RawDataType"
server:
  cdnUri: /dictionary/
spring:
  security:
    datawave:
      use-trusted-subject-headers: true