global:
  dockerRegistry:
    url: ghcr.io/nationalsecurityagency
  volumes:
    certificates:
      name: certificates
      destination: /data/certs
  initialization:
    image:
      name: busybox
      tag: 1.28
  certSecretName: certificates-secret
  pullSecrets:
    - dockerconfigjson-ghcr
  serviceDns:
    configuration:
      name: configuration
      port: 8888
    authorization:
      name: authorization
    cache:
      name: cache
      port: 8080


################################################################
# Default Values for Datawave Accumulo Microservice Deployment #
################################################################
image:
  name: datawave-accumulo-service
  pullPolicy: IfNotPresent
  tag: 4.0.2
args:
- "--spring.output.ansi.enabled=ALWAYS"
- "--spring.profiles.active=default,k8s,remoteauth"
livenessProbe:
  delaySeconds: 60
  periodSeconds: 5
  port: 8080
  scheme: HTTP
  uri: accumulo/mgmt/health
meta:
  name: accumulo-microservice
service:
  name: accumulo
readinessProbe:
  delaySeconds: 60
  periodSeconds: 5
  port: 8080
  scheme: HTTP
  uri: accumulo/mgmt/health
replication:
  maxSurge: 2
  maxUnavailable: 1
  replicaCount: 1
  revisionHistoryLimit: 10
restartPolicy: Always
  
####################################
# Default Values for Audit Service #
####################################

ports:
  http: 8080
  https: 8443
