#####################################
# DataWave Helm Chart Configuration #
#####################################

apiVersion: v2
name: datawave-monolith-umbrella
type: application
version: 1.0.1-SNAPSHOT

#################################
# Basic Metadata for this Chart #
#################################

appVersion: 7.9.0
description: Deploys The web stack of DataWave
icon: https://code.nsa.gov/datawave/images/datawave-logo.png

dependencies:
  - name: dwv-audit
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../audit
  - name: dwv-configuration
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../configuration
  - name: dwv-cache
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../cache
  - name: dwv-dictionary
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../dictionary
  - name: dwv-rabbitmq
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../rabbitmq
  - name: dwv-authorization
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../authorization
  - name: dwv-web
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../datawave-monolith