{{- if .Values.hdfs.nameNode.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hadoop.fullname" . }}-nn-ingress
  labels:
    app.kubernetes.io/component: monitor
  {{- with .Values.hdfs.nameNode.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
        pathType: Prefix
        backend:
          service:
            name: hdfs-nn
            port: 
              name: webhdfs
{{- else }}
        backend:
          serviceName: hdfs-nn
          servicePort: webhdfs
{{- end }}
    {{- if ne .Values.hdfs.nameNode.ingress.host "" }}
    host: {{ .Values.hdfs.nameNode.ingress.host }}
    {{- end }}
{{- end }}
