apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-hdfs-nn
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: hdfs-nn
spec:
  serviceName: {{ include "hadoop.fullname" . }}-hdfs-nn
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: hdfs-nn
  template:
    metadata:
      labels:
        app: {{ include "hadoop.name" . }}
        release: {{ .Release.Name }}
        component: hdfs-nn
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
      - name: init-zookeeper
        securityContext:
          runAsUser: 1000
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup zookeeper; do echo waiting for zookeeper; sleep 2; done"]
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hadoop.name" . }}
                release: {{ .Release.Name | quote }}
                component: hdfs-nn
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hadoop.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: hdfs-nn
        {{- end }}
      terminationGracePeriodSeconds: 0
      {{- with .Values.hdfs.nameNode.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: hdfs-nn
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
        - "/bin/sh"
        - "{{ .Values.global.volumes.hadoop_bootstrap.destination }}/bootstrap.sh"
        - "-d"
        resources:
          {{ toYaml .Values.hdfs.nameNode.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: 9870
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 9870
          initialDelaySeconds: 10
          timeoutSeconds: 2
        ports:
          - containerPort: 9870
        volumeMounts:
        {{- include "hadoop.volumeMount" $.Values.global.volumes.hadoop_bootstrap | nindent 8 }}
        {{- if .Values.persistence.nameNode.enabled }}
        - name: dfs
          mountPath: /usr/local/hadoop/data/
        {{- end }}
      volumes:
      {{- include "hadoop.volume" $.Values.global.volumes.hadoop_bootstrap | nindent 6 }}
  {{- if .Values.persistence.nameNode.enabled }}
  {{- with .Values.persistence.nameNode.definitions }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}