
{{- if .Values.config.postInstallCommands }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "hadoop.fullname" . }}-post-install-cmds
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "10"
  labels:
    app.kubernetes.io/component: hook
spec:
  restartPolicy: Never
  initContainers:
    - name: init-hdfs-nn
      securityContext:
        runAsUser: 1000
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup hdfs-nn; do echo waiting for hdfs-nn; sleep 2; done"]

  securityContext:
    runAsUser: 1000
  containers:
  - name: cmds
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: ["/bin/bash", "/cmds/run.sh"]
    volumeMounts:
    - name: cmds
      mountPath: /cmds
      readOnly: true
    - name: hadoop-config
      mountPath: /tmp/hadoop-config
    resources:
      {{- toYaml .Values.cmds.resources | nindent 6 }}
  volumes:
  - name: cmds
    secret:
      secretName: {{ include "hadoop.fullname" . }}-cmds
      optional: false
  - name: hadoop-config
    configMap:
      name: {{ .Values.global.hadoopConfigMap }}
     
  {{- with .Values.cmds.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cmds.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cmds.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.global.pullSecrets }}
  imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}
