
{{- if .Values.hadoop.config.postInstallCommands }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "hadoop.fullname" . }}-post-install-cmds
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "10"
  labels:
    app.kubernetes.io/component: hook
spec:
  restartPolicy: Never
  initContainers:
    - name: init-accumulo
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup hdfs-nn; do echo waiting for zookeeper; sleep 2; done"]

  containers:
  - name: cmds
    image: {{ .Values.hadoop.image.repository }}:{{ .Values.hadoop.image.tag }}
    imagePullPolicy: {{ .Values.hadoop.image.pullPolicy }}
    command: ["/bin/bash", "/cmds/run.sh"]
    volumeMounts:
    - name: cmds
      mountPath: /cmds
      readOnly: true
    resources:
      {{- toYaml .Values.hadoop.cmds.resources | nindent 6 }}
  volumes:
  - name: cmds
    secret:
      secretName: {{ include "hadoop.fullname" . }}-cmds
      optional: false
  {{- with .Values.hadoop.cmds.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.hadoop.cmds.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.hadoop.cmds.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.hadoop.image.pullSecrets }}
  imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}
