{{- define "hadoop.hadoopCommandsScript" -}}
#!/bin/bash -e
(while [[ $count -lt 150 && -z `curl -sf http://{{ include "hadoop.fullname" . }}-hdfs-dn:9864/jmx` ]]; do ((count=count+1)) ; echo "Waiting for {{ include "hadoop.fullname" . }}-hdfs-dn" ; sleep 2; done && [[ $count -lt 150 ]])
      [[ $? -ne 0 ]] && echo "Timeout waiting for hdfs-dn, exiting." && exit 1

{{range  .Values.hadoop.config.postInstallCommands }}
 {{ . }}
{{- end}}

{{- end -}}

{{- if .Values.hadoop.config.postInstallCommands }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hadoop.fullname" . }}-cmds
type: Opaque
data:
  run.sh: {{ include "hadoop.hadoopCommandsScript" . | b64enc }}
{{- end }}
