apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-nm
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: yarn-nm
spec:
  serviceName: {{ include "hadoop.fullname" . }}-yarn-nm
  replicas: {{ .Values.yarn.nodeManager.replicas }}
  selector:
    matchLabels:
      app: {{ include "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: yarn-nm
{{- if .Values.yarn.nodeManager.parallelCreate }}
  podManagementPolicy: Parallel
{{- end }}
  template:
    metadata:
      labels:
        app: {{ include "hadoop.name" . }}
        release: {{ .Release.Name }}
        component: yarn-nm
    spec:
      securityContext:
        runAsUser: 1000
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app:  {{ include "hadoop.name" . }}
                release: {{ .Release.Name | quote }}
                component: yarn-nm
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  {{ include "hadoop.name" . }}
                  release: {{ .Release.Name | quote }}
                  component: yarn-nm
        {{- end }}
      terminationGracePeriodSeconds: 0
      initContainers:
      - name: init-yarn-rm
        image: busybox:1.28
        securityContext:
          runAsUser: 1000
        command: ['sh', '-c', "until nslookup yarn-rm; do echo waiting for yarn-rm; sleep 2; done"]
      {{- with .Values.yarn.nodeManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: yarn-nm
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 8088
          name: web
        command:
           - "/bin/bash"
           - "{{ .Values.global.volumes.hadoop_bootstrap.destination }}/bootstrap.sh"
           - "-d"
        resources:
{{ toYaml .Values.yarn.nodeManager.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /node
            port: 8042
          initialDelaySeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /node
            port: 8042
          initialDelaySeconds: 10
          timeoutSeconds: 2
        env:
        - name: MY_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: yarn-nm
              resource: limits.cpu
              divisor: 1
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: yarn-nm
              resource: limits.memory
              divisor: 1M
        ports:
          - containerPort: 8088
          - containerPort: 8042
        volumeMounts:
        {{- include "hadoop.volumeMount" $.Values.global.volumes.hadoop_bootstrap | nindent 8 }}
      volumes:
      {{- include "hadoop.volume" $.Values.global.volumes.hadoop_bootstrap | nindent 6 }}