####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: ConfigMap

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-ingest-env-configmap"

##########################
# Configuration Map Data #
##########################

data: 

  #################################################
  # Kubernetes-Specific Application Configuration #
  #################################################

  ingest-env.sh: |
    #!/bin/bash
    
    #Directory in which to place the lock files
    export LOCK_FILE_DIR={{ .Values.config.lockFileDir}}

    HADOOP_HOME="{{ .Values.config.hadoopHome }}"
    MAPRED_HOME="{{ .Values.config.mapredHome }}"
    MAPRED_HOME="${MAPRED_HOME:-$HADOOP_HOME}"
    HADOOP_CONF_DIR="/usr/local/hadoop/conf"
    USERNAME="{{ .Values.config.accumuloUser }}"
    WAREHOUSE_ACCUMULO_HOME="{{ .Values.config.accumuloDir }}"
    WAREHOUSE_HDFS_NAME_NODE="{{ .Values.config.hdfsNamenode }}"
    WAREHOUSE_JOBTRACKER_NODE="{{ .Values.config.jobTracker }}"
    WAREHOUSE_ZOOKEEPERS="{{ .Values.config.zookeeper }}"
    WAREHOUSE_INSTANCE_NAME="{{ .Values.config.instanceName }}"
    WAREHOUSE_HADOOP_CONF="{{ .Values.config.hadoopConfDif }}"
    WAREHOUSE_HADOOP_CONF="${WAREHOUSE_HADOOP_CONF:-$WAREHOUSE_HADOOP_HOME/conf}"

    INGEST_ACCUMULO_HOME="{{ .Values.config.accumuloDir }}"
    INGEST_HDFS_NAME_NODE="{{ .Values.config.hdfsNamenode }}"
    INGEST_JOBTRACKER_NODE="{{ .Values.config.jobTracker }}"
    INGEST_ZOOKEEPERS="{{ .Values.config.zookeeper }}"
    INGEST_INSTANCE_NAME="{{ .Values.config.instanceName }}"

    INGEST_HADOOP_CONF="{{ .Values.config.hadoopConfDif }}"
    INGEST_HADOOP_CONF="${INGEST_HADOOP_CONF:-$INGEST_HADOOP_HOME/conf}"

    BULK_INGEST_DATA_TYPES="{{ .Values.config.bulkDataTypes }}"
    LIVE_INGEST_DATA_TYPES="{{ .Values.config.liveDataTypes  }}"
    
    {{ .Values.config.ingestEnv | nindent 4}}