
apiVersion: v1
kind: Service
metadata:
  name: ingestmaster
  labels:
    {{- include "datawave.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  selector:
    {{- include "datawave.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22

