
{{- define "datawave.datawaveInstallScript" -}}
#!/bin/bash -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

echo "Creating logs directory and opening permissions"
mkdir -p /srv/logs/ingest
chmod 777 -R /srv/logs/

chmod +w /opt/datawave-ingest/current/config/*
cp -Lr /opt/datawave-ingest/mounted-config/* /opt/datawave-ingest/current/config
chmod -w /opt/datawave-ingest/current/config/*

echo "Create Accumulo Namespace"
/opt/accumulo/bin/accumulo shell -u root -p {{ .Values.config.accumuloPassword }} -e "createnamespace datawave"

echo "Set Classpath Context"
/opt/accumulo/bin/accumulo shell -u root -p {{ .Values.config.accumuloPassword }} -e "config -s  table.class.loader.context=datawave"

echo "resetting hadoop home to use mounted config"
export HADOOP_CONF_DIR=/usr/local/hadoop/conf/

echo "Symlinking Password file"
ln -s /cmds/ingest-passwd.sh /opt/datawave-ingest/ingest-passwd.sh

echo "Creating Flag File directory and making it owned by datawave"
mkdir -p /srv/data/datawave/flags

echo "Create datawave tables"
/opt/datawave-ingest/current/bin/ingest/create-all-tables.sh 

echo "loading job cache"
/opt/datawave-ingest/current/bin/ingest/load-job-cache.sh
  
if [[ {{ (.Values.config.sharedConfig).claim }} != "" ]]; then
  echo "synchronizing shared config to pvc {{ .Values.config.sharedConfig.claim }} at {{ .Values.config.sharedConfig.path }}"
  cp -Lr /opt/datawave-ingest/current/config/* {{ .Values.config.sharedConfig.path }}
else
  echo "skipping shared config pvc sync"
fi
  
echo "Starting datawave ingest"
/opt/datawave-ingest/current/bin/system/start-all.sh

tail -f /dev/null


{{- end -}}


{{- define "datawave.passwdfile" -}}
#TODO update to pass passwords in as secrets.
export PASSWORD={{ .Values.config.accumuloPassword }}
export KEYSTORE_PASSWORD=root
export TRUSTSTORE_PASSWORD=root

{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datawave.fullname" . }}-cmds
  labels:
    {{- include "datawave.labels" . | nindent 4 }}
type: Opaque
data:
  run.sh: {{ include "datawave.datawaveInstallScript" . | b64enc }}
  ingest-passwd.sh: {{ include "datawave.passwdfile" . | b64enc }}