
apiVersion: v1
kind: Service
metadata:
  name: accumulo-manager
  labels:
    {{- include "accumulo.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  selector:
    {{- include "accumulo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
