# Copyright 2020 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accumulo.fullname" . }}-monitor
  labels:
    {{- include "accumulo.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitor
spec:
  replicas: {{ .Values.accumulo.monitor.replicaCount }}
  selector:
    matchLabels:
      {{- include "accumulo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: monitor
  template:
    metadata:
      labels:
        {{- include "accumulo.labels" . | nindent 8 }}
        app.kubernetes.io/component: monitor
    spec:
      securityContext:
        runAsUser: 1001
      initContainers:
      - name: init-accumulo
        securityContext:
          runAsUser: 1000
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup accumulo-master; do echo waiting for accumulo; sleep 2; done; sleep 20"]
      volumes:
        - name: hadoop-config
          configMap:
            name: {{ .Values.accumulo.hadoopConfigMap }}
        - name: config
          configMap:
            name: accumulo-config
      containers:
      - name: accumulo-monitor
        image: {{ .Values.accumulo.image.repository }}:{{ .Values.accumulo.image.tag }}
        imagePullPolicy: {{ .Values.accumulo.image.pullPolicy }}
        args: 
         - monitor
        volumeMounts:
        - name: hadoop-config
          mountPath: /opt/hadoop/conf
        - name: config
          mountPath: /opt/accumulo/conf
        env:
        - name: HADOOP_CLASSPATH
          value: {{ .Values.accumulo.hadoop.classpath }}
        - name: HADOOP_CONF_DIR
          value: /opt/hadoop/conf
        - name: ACCUMULO_CONF_DIR
          value: {{ .Values.accumulo.config.path }}
        ports:
        - name: http
          protocol: TCP
          containerPort: 9995
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.accumulo.monitor.resources | nindent 10 }}
      {{- with .Values.accumulo.monitor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.monitor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.monitor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
