
{{- if or .Values.config.userManagement.users .Values.config.postInstallCommands }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "accumulo.fullname" . }}-post-install-cmds
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "20"
  labels:
    {{- include "accumulo.labels" . | nindent 4 }}
    app.kubernetes.io/component: hook
spec:
  securityContext:
    runAsUser: 1001
  restartPolicy: Never
  initContainers:
    - name: init-accumulo
      securityContext:
        runAsUser: 1001
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup accumulo-manager; do echo waiting for accumulo; sleep 2; done"]
  containers:
  - name: cmds
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: ["/bin/bash", "/cmds/run.sh"]
    volumeMounts:
    - name: hadoop-config
      mountPath: /opt/hadoop/conf
    - name: config
      mountPath: /opt/accumulo/conf
    - name: cmds
      mountPath: /cmds
      readOnly: true
    env:
    - name: HADOOP_CLASSPATH
      value: {{ .Values.hadoop.classpath }}
    - name: HADOOP_CONF_DIR
      value: /opt/hadoop/conf
    - name: ACCUMULO_CONF_DIR
      value: {{ .Values.config.path }}
    resources:
      {{- toYaml .Values.cmds.resources | nindent 6 }}
  volumes:
  - name: hadoop-config
    configMap:
      name: {{ .Values.hadoopConfigMap }}
  - name: config
    configMap:
      name: accumulo-config
  - name: cmds
    secret:
      secretName: {{ include "accumulo.fullname" . }}-cmds
      optional: false
  {{- with .Values.cmds.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cmds.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cmds.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.global.pullSecrets }}
  imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}
