{{- with .Values.clusters }}
{{ range .}}
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: {{ .name }}
spec:
  secretName: {{ .secretName }}
  tlsUseSelfSigned: {{ .tlsUseSelfSigned }}
  instances: {{ .instances }}
  router:
    instances: {{ .router.instances }}
{{- if .claimTemplateOverride.enabled }}
  datadirVolumeClaimTemplate:
    storageClassName: {{ .claimTemplateOverride.storageClass }}
    accessModes: 
      - {{ .claimTemplateOverride.accessMode }}
    resources:
      requests:
        storage: {{ .claimTemplateOverride.size }}
{{- end }}
  {{- if .backup.enabled }}
  backupProfiles:
    - name: {{ .backup.name }}
      dumpInstance:
        dumpOptions:
          excludeTables: {{ .backup.excludeTables }}
        storage:
          persistentVolumeClaim:
            claimName: {{ .backup.claimName }}
  backupSchedules:
    - name: {{ .backup.schedule.name }}
      schedule: {{ .backup.schedule.cron }}
      backupProfileName: {{ .backup.name }}
      enabled: {{ .backup.schedule.enabled }}
  {{- end }}
{{- end }}
{{- end }}