{{- with .Values.clusters }}
{{ range .}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}-mysql-script-init
  labels:
    app: {{ .name }}
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.28
          command: ["sh", "-c"]
          args: [
            "until nc -z $MYSQL_HOST 3306; do echo waiting for MySQL; sleep 5; done;"
          ]
          env:
            - name: MYSQL_HOST
              value: {{ .name }}
        - name: create-cluster-users
          image: {{ $.Values.init.image.name  }}:{{ $.Values.init.image.tag  }}
          env:
            - name: MYSQL_HOST
              value: {{ .name }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: rootUser
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: rootPassword
          {{- range .databaseUsers }}
            - name: MYSQL_PASSWORD_{{ .name | upper | replace "-" "_" }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKeyRef }}
          {{- end }}
          command: ["sh", "-c"]
          args: ["mysqlsh $MYSQL_USER@{{ .name }} --sql --password=$MYSQL_PASSWORD -f /scripts/script.sql"]
          volumeMounts:
            - name: init-script
              mountPath: /scripts
              readOnly: true
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      {{- with $.Values.global.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: mysql-init-complete
          image: busybox:1.28
          command: ["sh", "-c"]
          args: ["echo mysql initialization complete"]
      restartPolicy: Never
      volumes:
        - name: init-script
          configMap:
            name: {{ .name }}-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-init-script
  labels:
    app: {{ .name }}
data:
  script.sql: |
    {{- $users := (.databaseUsers | default (list)) }}
    {{- range $users }}
    {{- $dbUser := .name }}
    CREATE USER IF NOT EXISTS '{{ .name }}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD_{{ .name | upper | replace "-" "_" }}}';
    {{- range .databases }}
    CREATE DATABASE IF NOT EXISTS {{ . }};
    GRANT ALL PRIVILEGES ON {{ . }}.* TO '{{ $dbUser }}'@'%' WITH GRANT OPTION;
    {{- end }}
    {{- end }}
    {{- if .initScript }}
    {{ .initScript |  nindent 4 }}
    {{- else if not $users }}
    SELECT 1;
    {{- end }}
{{- end }}
{{- end }}
