####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Service

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Values.auditService.meta.name }}"
  labels:
    application: "{{ .Values.auditService.meta.name }}"

##################################
# Complete Service Specification #
##################################

spec:

  ###############################
  # Pod Selection Configuration #
  ###############################

  selector:
    application: "{{ .Values.auditDeployment.meta.name }}"

  ##############################
  # Service Port Configuration #
  ##############################

  ports:

    - name: http
      port: {{ .Values.auditService.ports.http }}
      targetPort: 8080

    - name: https
      port: {{ .Values.auditService.ports.https }}
      targetPort: 8443
