####################################
# Core Helm Template Configuration #
####################################

apiVersion: apps/v1
kind: Deployment

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-{{ .Values.web.accumuloDeployment.meta.name }}"
  labels:
    application: "{{ .Chart.Name }}-{{ .Values.web.accumuloDeployment.meta.name }}"

#####################################
# Complete Deployment Specification #
#####################################

spec:

  ######################################
  # Replication / Update Configuration #
  ######################################

  replicas: {{ .Values.web.accumuloDeployment.replication.replicaCount }}
  revisionHistoryLimit: {{ .Values.web.accumuloDeployment.replication.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.web.accumuloDeployment.replication.maxSurge }}
      maxUnavailable: {{ .Values.web.accumuloDeployment.replication.maxUnavailable }}

  ###################################
  # Resource Selector Configuration #
  ###################################

  selector:
    matchLabels:
      application: "{{ .Chart.Name }}-{{ .Values.web.accumuloDeployment.meta.name }}"
  
  #####################################
  # Deployment Template Configuration #
  #####################################

  template:

    ##################################################
    # Basic Metadata for this Deployment's Resources #
    ##################################################

    metadata:
      labels:
        application: "{{ .Chart.Name }}-{{ .Values.web.accumuloDeployment.meta.name }}"

    #######################################
    # Deployment Resources Specifications #
    #######################################

    spec:
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: "{{ .Values.web.accumuloDeployment.restartPolicy }}"

      ##############################################
      # Containers Associated with this Deployment #
      ##############################################
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: "{{ .Chart.Name }}-{{ .Values.web.accumuloDeployment.meta.name }}"
          args:
            - "--spring.output.ansi.enabled=ALWAYS"
            - "--spring.profiles.active={{ .Values.web.accumuloDeployment.profiles }}"
          image: "{{ .Values.web.dockerRegistry.url }}{{ .Values.web.accumuloDeployment.image.name }}:{{ .Values.web.accumuloDeployment.image.tag }}"
          imagePullPolicy: "{{ .Values.web.accumuloDeployment.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              path: "{{ .Values.web.accumuloDeployment.livenessProbe.uri }}"
              port: {{ .Values.web.accumuloDeployment.livenessProbe.port }}
              scheme: "{{ .Values.web.accumuloDeployment.livenessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.web.accumuloDeployment.livenessProbe.delaySeconds }}
            periodSeconds: {{ .Values.web.accumuloDeployment.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.web.accumuloDeployment.readinessProbe.uri }}"
              port: {{ .Values.web.accumuloDeployment.readinessProbe.port }}
              scheme: "{{ .Values.web.accumuloDeployment.readinessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.web.accumuloDeployment.readinessProbe.delaySeconds }}
            periodSeconds: {{ .Values.web.accumuloDeployment.readinessProbe.periodSeconds }}
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          env:
            - name: ACCUMULO_PASSWORD
              value: {{ .Values.web.accumulo.password }} 
            - name: HADOOP_CLASSPATH
              value: {{ .Values.web.hadoop.classpath }}
            - name: KEYSTORE
              value: {{ .Values.web.volumes.certificates.destination }}/keystore.p12
            - name: KEYSTORE_TYPE
              value: PKCS12
            - name: KEYSTORE_PASSWORD
              value: {{ .Values.web.certificates.keystorePassword }} 
            - name: TRUSTSTORE
              value: {{ .Values.web.volumes.certificates.destination }}/truststore.jks
            - name: TRUSTSTORE_TYPE
              value: JKS
            - name: TRUSTSTORE_PASSWORD
              value: {{ .Values.web.certificates.truststorePassword }} 
            - name: CONFIG_SERVER_URL
              value: "http://{{ .Chart.Name }}-{{ .Values.web.configurationDeployment.meta.name }}:{{ .Values.web.configurationService.ports.default }}/configserver"
            - name: ZOOKEEPER_HOST
              value: "{{ .Values.web.zookeeper.quorum }}"
          volumeMounts:
            - name: "{{ .Chart.Name }}-{{ .Values.web.volumes.certificates.name }}"
              mountPath: "{{ .Values.web.volumes.certificates.destination }}"
              readOnly: true
            - name: hadoop-config
              mountPath: /etc/hadoop/conf
            - name: "{{ .Chart.Name }}-web-runtime-config"
              mountPath: /opt/jboss/wildfly/runtime-config.cli
              subPath: runtime-config.cli
            - name: logs
              mountPath: /logs

      #############################################################
      # Initialization Containers Associated with this Deployment #
      #############################################################

      initContainers:
        - name: init-accumulo
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup accumulo-master; do echo waiting for accumulo; sleep 2; done"]

        - name: "{{ .Chart.Name }}-init-authorization"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", "until nslookup {{ .Chart.Name }}-{{ .Values.web.authorizationService.meta.name }}; do echo 'Waiting for Authorization...'; sleep 2; done" ]

        - name: "{{ .Chart.Name }}-init-configuration"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", "until nslookup {{ .Chart.Name }}-{{ .Values.web.configurationService.meta.name }}; do echo 'Waiting for Configuration...'; sleep 2; done" ]
          
      
      ###########################################
      # Volumes Associated with this Deployment #
      ###########################################

      volumes:
        - name: logs
          emptyDir:
            sizeLimit: 10G
        - name: "{{ .Chart.Name }}-{{ .Values.web.volumes.certificates.name }}"
          secret:
            {{ if not .Values.web.certificates.externalSecret.enabled }}
            secretName: "{{ .Chart.Name }}-{{ .Values.web.certificatesSecret.meta.name }}"
            {{ else }}
            secretName: {{ .Values.web.certificates.exernalSecret.name }}
            {{ end }}
            optional: false
        - name: hadoop-config
          configMap:
            name: "{{ .Values.web.volumes.hadoop.configMapName }}"
        - name: "{{ .Chart.Name }}-web-runtime-config"
          configMap:
            name: "{{ .Chart.Name }}-web-runtime-config"

