####################################
# Core Helm Template Configuration #
####################################

apiVersion: apps/v1
kind: Deployment

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Values.authorizationDeployment.meta.name }}"
  labels:
    application: "{{ .Values.authorizationDeployment.meta.name }}"

#####################################
# Complete Deployment Specification #
#####################################

spec:

  ######################################
  # Replication / Update Configuration #
  ######################################

  replicas: {{ .Values.authorizationDeployment.replication.replicaCount }}
  revisionHistoryLimit: {{ .Values.authorizationDeployment.replication.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.authorizationDeployment.replication.maxSurge }}
      maxUnavailable: {{ .Values.authorizationDeployment.replication.maxUnavailable }}

  ###################################
  # Resource Selector Configuration #
  ###################################

  selector:
    matchLabels:
      application: "{{ .Values.authorizationDeployment.meta.name }}"
  
  #####################################
  # Deployment Template Configuration #
  #####################################

  template:

    ##################################################
    # Basic Metadata for this Deployment's Resources #
    ##################################################

    metadata:
      labels:
        application: "{{ .Values.authorizationDeployment.meta.name }}"

    #######################################
    # Deployment Resources Specifications #
    #######################################

    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      securityContext:
        runAsUser: 1000
      restartPolicy: "{{ .Values.authorizationDeployment.restartPolicy }}"

      ##############################################
      # Containers Associated with this Deployment #
      ##############################################

      containers:

        - name: "{{ .Values.authorizationDeployment.meta.name }}"
          args:
            - "--spring.output.ansi.enabled=ALWAYS"
            - "--spring.profiles.active={{ .Values.authorizationDeployment.profiles }}"
          env:
            - name: CONFIG_SERVER_URL
              value: "http://{{ .Values.configurationDeployment.meta.name }}:{{ .Values.configurationService.ports.default }}/configserver"
          image: "{{ .Values.dockerRegistry.url }}/{{ .Values.authorizationDeployment.image.name }}:{{ .Values.authorizationDeployment.image.tag }}"
          imagePullPolicy: "{{ .Values.authorizationDeployment.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              path: "{{ .Values.authorizationDeployment.livenessProbe.uri }}"
              port: {{ .Values.authorizationDeployment.livenessProbe.port }}
              scheme: "{{ .Values.authorizationDeployment.livenessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.authorizationDeployment.livenessProbe.delaySeconds }}
            periodSeconds: {{ .Values.authorizationDeployment.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.authorizationDeployment.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.authorizationDeployment.readinessProbe.uri }}"
              port: {{ .Values.authorizationDeployment.readinessProbe.port }}
              scheme: "{{ .Values.authorizationDeployment.readinessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.authorizationDeployment.readinessProbe.delaySeconds }}
            periodSeconds: {{ .Values.authorizationDeployment.readinessProbe.periodSeconds }}
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - name: "{{ .Values.volumes.certificates.name }}"
              mountPath: "{{ .Values.volumes.certificates.destination }}"
              readOnly: true

      #############################################################
      # Initialization Containers Associated with this Deployment #
      #############################################################

      initContainers:
        - name: init-accumulo
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup accumulo-manager; do echo waiting for accumulo; sleep 2; done"]
        - name: "{{ .Chart.Name }}-init-cache"
          image: "{{ .Values.initialization.image.name }}:{{ .Values.initialization.image.tag }}"
          command: [ "sh", "-c", " until nslookup {{ .Values.cacheService.meta.name }}; do echo 'Waiting for Cache...'; sleep 2; done" ]
        - name: "{{ .Chart.Name }}-init-configuration"
          image: "{{ .Values.initialization.image.name }}:{{ .Values.initialization.image.tag }}"
          command: [ "sh", "-c", "until nslookup {{ .Values.configurationService.meta.name }}; do echo 'Waiting for Configuration...'; sleep 2; done" ]
        - name: "{{ .Chart.Name }}-init-messaging"
          image: "{{ .Values.initialization.image.name }}:{{ .Values.initialization.image.tag }}"
          command: [ "sh", "-c", "until nslookup  {{ .Values.messagingService.meta.name }}; do echo 'Waiting for Messaging...'; sleep 2; done" ]
      
      ###########################################
      # Volumes Associated with this Deployment #
      ###########################################

      volumes:
        - name: logs
          emptyDir:
            sizeLimit: 5G
        - name: "{{ .Values.volumes.certificates.name }}"
          secret:
            {{ if not .Values.certificates.externalSecret.enabled }}
            secretName: "{{ .Values.certificatesSecret.meta.name }}"
            {{ else }}
            secretName: {{ .Values.certificates.externalSecret.name }}
            {{ end }}
            optional: false
