{{ if not .Values.certificates.externalSecret.enabled }}
           
####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Secret
######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Values.certificatesSecret.meta.name }}"
type: Opaque
##########################
# Configuration Map Data #
##########################

data: 
  keystore.p12: |-
    {{ .Values.certificates.encodedKeystore }}
  truststore.jks: |-
    {{ .Values.certificates.encodedTruststore }}
{{ end }}