####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Service

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-{{ .Values.web.datawaveService.meta.name }}"
  labels:
    application: "{{ .Chart.Name }}-{{ .Values.web.datawaveService.meta.name }}"

##################################
# Complete Service Specification #
##################################

spec:

  ###############################
  # Pod Selection Configuration #
  ###############################

  selector:
    application: "{{ .Chart.Name }}-{{ .Values.web.datawaveDeployment.meta.name }}"

  ##############################
  # Service Port Configuration #
  ##############################

  ports:

    - name: https
      port: {{ .Values.web.datawaveService.ports.https }}
      targetPort: 8443
