####################################
# Core Helm Template Configuration #
####################################
{{- if .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-datawave-ingress"
  annotations:
    {{- with .Values.web.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    application: "{{ .Chart.Name }}-{{ .Values.web.datawaveDeployment.meta.name }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    {{- with .Values.web.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}


####################################
# Ingress Controller Specification #
####################################
spec:
  ingressClassName: "{{ .Values.web.ingress.services.ingressClassName }}"
  rules:
  - host: {{ .Values.web.ingress.host }}
    http:
      paths:
        - path: /DataWave
          pathType: Prefix
          backend:
            service:
              name: "{{ .Chart.Name }}-{{ .Values.web.datawaveService.meta.name }}-http"
              port:
                number: 8080
  {{- if .Values.web.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.web.ingress.webservice.domain }}
  {{- end }}
{{- end }}