####################################
# Core Helm Template Configuration #
####################################
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-dictionary-ingress"
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"


####################################
# Ingress Controller Specification #
####################################

spec:

  ################################################
  # Transport-Layer Security (TLS) Configuration #
  ################################################


  #########################################
  # Ingress Controller Rule Configuration #
  #########################################
  ingressClassName: {{ .Values.ingress.services.ingressClassName }}
  rules:
    - host: "{{ .Values.ingress.dictionary.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.dictionaryService.meta.name }}"
                port: 
                  number: {{ .Values.dictionaryService.ports.https }}
{{- end }}

