####################################
# Core Helm Template Configuration #
####################################

apiVersion: apps/v1
kind: Deployment

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-{{ .Values.web.executorDeployment.meta.name }}"
  labels:
    application: "{{ .Chart.Name }}-{{ .Values.web.executorDeployment.meta.name }}"

#####################################
# Complete Deployment Specification #
#####################################

spec:

  ######################################
  # Replication / Update Configuration #
  ######################################

  replicas: {{ .Values.web.executorDeployment.replication.replicaCount }}
  revisionHistoryLimit: {{ .Values.web.executorDeployment.replication.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.web.executorDeployment.replication.maxSurge }}
      maxUnavailable: {{ .Values.web.executorDeployment.replication.maxUnavailable }}

  ###################################
  # Resource Selector Configuration #
  ###################################

  selector:
    matchLabels:
      application: "{{ .Chart.Name }}-{{ .Values.web.executorDeployment.meta.name }}"
  
  #####################################
  # Deployment Template Configuration #
  #####################################

  template:

    ##################################################
    # Basic Metadata for this Deployment's Resources #
    ##################################################

    metadata:
      labels:
        application: "{{ .Chart.Name }}-{{ .Values.web.executorDeployment.meta.name }}"

    #######################################
    # Deployment Resources Specifications #
    #######################################

    spec:
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      restartPolicy: "{{ .Values.web.executorDeployment.restartPolicy }}"

      ##############################################
      # Containers Associated with this Deployment #
      ##############################################

      containers:
        - name: "{{ .Chart.Name }}-{{ .Values.web.executorDeployment.meta.name }}"
          #TODO use same yaml for pool1 and pool2
          command:
          args:
            - --spring.application.name=executor-pool1
            - --spring.cloud.config.name=executor
            - "--spring.output.ansi.enabled=ALWAYS"
            - "--spring.profiles.active={{ .Values.web.executorDeployment.profiles }}"
          env:
            - name: ZOOKEEPER_HOST
              value: "{{ .Values.web.zookeeper.quorum }}"
            - name: HADOOP_HOST
              value: hdfs-nn
            - name: HADOOP_CONF_DIR
              value: /etc/hadoop/conf
            - name: BACKEND
              value: kafka
            - name: CONFIG_SERVER_URL
              value: "http://{{ .Chart.Name }}-{{ .Values.web.configurationDeployment.meta.name }}:{{ .Values.web.configurationService.ports.default }}/configserver"
          
          image: "{{ .Values.web.dockerRegistry.url }}{{ .Values.web.executorDeployment.image.name }}:{{ .Values.web.executorDeployment.image.tag }}"
          imagePullPolicy: "{{ .Values.web.executorDeployment.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              path: "{{ .Values.web.executorDeployment.livenessProbe.uri }}"
              port: {{ .Values.web.executorDeployment.livenessProbe.port }}
              scheme: "{{ .Values.web.executorDeployment.livenessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.web.executorDeployment.livenessProbe.delaySeconds }}
            periodSeconds: {{ .Values.web.executorDeployment.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.web.auditDeployment.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.web.executorDeployment.readinessProbe.uri }}"
              port: {{ .Values.web.executorDeployment.readinessProbe.port }}
              scheme: "{{ .Values.web.executorDeployment.readinessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.web.executorDeployment.readinessProbe.delaySeconds }}
            periodSeconds: {{ .Values.web.executorDeployment.readinessProbe.periodSeconds }}
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - name: logs
              mountPath: /logs
            - name: "{{ .Chart.Name }}-{{ .Values.web.volumes.certificates.name }}"
              mountPath: "{{ .Values.web.volumes.certificates.destination }}"
              readOnly: true
            - name: hadoop-config
              mountPath: /etc/hadoop/conf

      #############################################################
      # Initialization Containers Associated with this Deployment #
      #############################################################

      initContainers:
        - name: "{{ .Chart.Name }}-init-cache"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", " until nslookup {{ .Chart.Name }}-{{ .Values.web.cacheService.meta.name }}; do echo 'Waiting for Cache...'; sleep 2; done" ]
        - name: "{{ .Chart.Name }}-init-configuration"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", "until nslookup {{ .Chart.Name }}-{{ .Values.web.configurationService.meta.name }}; do echo 'Waiting for Configuration...'; sleep 2; done" ]
        - name: "{{ .Chart.Name }}-init-accumulo"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", "until nslookup accumulo-master; do echo 'Waiting for Accumulo...'; sleep 2; done" ]
        - name: "{{ .Chart.Name }}-init-metrics"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", " until nslookup {{ .Chart.Name }}-{{ .Values.web.metricsService.meta.name }}; do echo 'Waiting for Metrics...'; sleep 2; done" ]
        - name: "{{ .Chart.Name }}-init-authorization"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", " until nslookup {{ .Chart.Name }}-{{ .Values.web.authorizationService.meta.name }}; do echo 'Waiting for Authorization...'; sleep 2; done" ]
        - name: "{{ .Chart.Name }}-init-kafka"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", " until nslookup {{ .Chart.Name }}-{{ .Values.web.kafkaService.meta.name }}; do echo 'Waiting for Kafka...'; sleep 2; done" ]
        - name: "{{ .Chart.Name }}-init-executor"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", " until nslookup {{ .Chart.Name }}-{{ .Values.web.executorService.meta.name }}; do echo 'Waiting for Executor Service...'; sleep 2; done" ]

      ###########################################
      # Volumes Associated with this Deployment #
      ###########################################

      volumes:
        - name: logs
          emptyDir:
            sizeLimit: 10G        
        - name: "{{ .Chart.Name }}-{{ .Values.web.volumes.certificates.name }}"
          secret:
            {{ if not .Values.web.certificates.externalSecret.enabled }}
            secretName: "{{ .Chart.Name }}-{{ .Values.web.certificatesSecret.meta.name }}"
            {{ else }}
            secretName: {{ .Values.web.certificates.exernalSecret.name }}
            {{ end }}
            optional: false
        - name: hadoop-config
          configMap:
            name: "{{ .Values.web.volumes.hadoop.configMapName }}"
