####################################
# Core Helm Template Configuration #
####################################

apiVersion: apps/v1
kind: Deployment

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-{{ .Values.web.kafdropDeployment.meta.name }}"
  labels:
    application: "{{ .Chart.Name }}-{{ .Values.web.kafdropDeployment.meta.name }}"

#####################################
# Complete Deployment Specification #
#####################################

spec:

  ######################################
  # Replication / Update Configuration #
  ######################################

  replicas: {{ .Values.web.kafdropDeployment.replication.replicaCount }}
  revisionHistoryLimit: {{ .Values.web.kafdropDeployment.replication.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.web.kafdropDeployment.replication.maxSurge }}
      maxUnavailable: {{ .Values.web.kafdropDeployment.replication.maxUnavailable }}

  ###################################
  # Resource Selector Configuration #
  ###################################

  selector:
    matchLabels:
      application: "{{ .Chart.Name }}-{{ .Values.web.kafdropDeployment.meta.name }}"
  
  #####################################
  # Deployment Template Configuration #
  #####################################

  template:

    ##################################################
    # Basic Metadata for this Deployment's Resources #
    ##################################################

    metadata:
      labels:
        application: "{{ .Chart.Name }}-{{ .Values.web.kafdropDeployment.meta.name }}"

    #######################################
    # Deployment Resources Specifications #
    #######################################

    spec:
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      securityContext:
        runAsUser: 1000
      restartPolicy: "{{ .Values.web.kafdropDeployment.restartPolicy }}"
      ##############################################
      # Containers Associated with this Deployment #
      ##############################################

      containers:

        - name: "{{ .Chart.Name }}-{{ .Values.web.kafdropDeployment.meta.name }}"
          image: "{{ .Values.web.kafdropDeployment.image.name }}:{{ .Values.web.kafdropDeployment.image.tag }}"
          imagePullPolicy: "{{ .Values.web.kafdropDeployment.image.pullPolicy }}"
          resources: {}
