####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: ConfigMap

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Values.messagingMap.meta.name }}"
  labels:
    application: "{{ .Values.messagingMap.meta.name }}"

##########################
# Configuration Map Data #
##########################

data: 

  #########################################
  # RabbitMQ Enabled Plugin Configuration #
  #########################################

  enabled_plugins: |
    [rabbitmq_management].
  
  ##################################
  # RabbitMQ General Configuration #
  ##################################

  rabbitmq.conf: |
    loopback_users.guest = false
    queue_master_locator = min-masters
