####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Service

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-{{ .Values.web.messagingService.meta.name }}"
  labels:
    application: "{{ .Chart.Name }}-{{ .Values.web.messagingService.meta.name }}"

##################################
# Complete Service Specification #
##################################

spec:

  ###############################
  # Pod Selection Configuration #
  ###############################

  selector:
    application: "{{ .Chart.Name }}-{{ .Values.web.messagingDeployment.meta.name }}"

  ##############################
  # Service Port Configuration #
  ##############################

  ports:

    - name: amqp
      port: {{ .Values.web.messagingService.ports.amqp }}
      targetPort: 5672

    - name: mgmt
      port: {{ .Values.web.messagingService.ports.mgmt }}
      targetPort: 15672
