####################################
# Core Helm Template Configuration #
####################################

apiVersion: apps/v1
kind: Deployment

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-{{ .Values.web.modificationDeployment.meta.name }}"
  labels:
    application: "{{ .Chart.Name }}-{{ .Values.web.modificationDeployment.meta.name }}"

#####################################
# Complete Deployment Specification #
#####################################

spec:

  ######################################
  # Replication / Update Configuration #
  ######################################

  replicas: {{ .Values.web.modificationDeployment.replication.replicaCount }}
  revisionHistoryLimit: {{ .Values.web.modificationDeployment.replication.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.web.modificationDeployment.replication.maxSurge }}
      maxUnavailable: {{ .Values.web.modificationDeployment.replication.maxUnavailable }}

  ###################################
  # Resource Selector Configuration #
  ###################################

  selector:
    matchLabels:
      application: "{{ .Chart.Name }}-{{ .Values.web.modificationDeployment.meta.name }}"
  
  #####################################
  # Deployment Template Configuration #
  #####################################

  template:

    ##################################################
    # Basic Metadata for this Deployment's Resources #
    ##################################################

    metadata:
      labels:
        application: "{{ .Chart.Name }}-{{ .Values.web.modificationDeployment.meta.name }}"

    #######################################
    # Deployment Resources Specifications #
    #######################################

    spec:
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: "{{ .Values.web.modificationDeployment.restartPolicy }}"

      ##############################################
      # Containers Associated with this Deployment #
      ##############################################
      securityContext:
        runAsUser: 1000
      containers:
        - name: "{{ .Chart.Name }}-{{ .Values.web.modificationDeployment.meta.name }}"
          args:
            - "--spring.output.ansi.enabled=ALWAYS"
            - "--spring.profiles.active={{ .Values.web.modificationDeployment.profiles }}"
          env:
            - name: CONFIG_SERVER_URL
              value: "http://{{ .Chart.Name }}-{{ .Values.web.configurationDeployment.meta.name }}:{{ .Values.web.configurationService.ports.default }}/configserver"
            - name: ZOOKEEPER_HOST
              value: "{{ .Values.web.zookeeper.quorum }}"
          image: "{{ .Values.web.dockerRegistry.url }}{{ .Values.web.modificationDeployment.image.name }}:{{ .Values.web.modificationDeployment.image.tag }}"
          imagePullPolicy: "{{ .Values.web.modificationDeployment.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              path: "{{ .Values.web.modificationDeployment.livenessProbe.uri }}"
              port: {{ .Values.web.modificationDeployment.livenessProbe.port }}
              scheme: "{{ .Values.web.modificationDeployment.livenessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.web.modificationDeployment.livenessProbe.delaySeconds }}
            periodSeconds: {{ .Values.web.modificationDeployment.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.web.modificationDeployment.readinessProbe.uri }}"
              port: {{ .Values.web.modificationDeployment.readinessProbe.port }}
              scheme: "{{ .Values.web.modificationDeployment.readinessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.web.modificationDeployment.readinessProbe.delaySeconds }}
            periodSeconds: {{ .Values.web.modificationDeployment.readinessProbe.periodSeconds }}
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - name: logs
              mountPath: /logs
            - name: "{{ .Chart.Name }}-{{ .Values.web.volumes.certificates.name }}"
              mountPath: "{{ .Values.web.volumes.certificates.destination }}"
              readOnly: true

      #############################################################
      # Initialization Containers Associated with this Deployment #
      #############################################################

      initContainers:
        - name: init-accumulo
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup accumulo-master; do echo waiting for accumulo; sleep 2; done"]


        - name: "{{ .Chart.Name }}-init-authorization"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", "until nslookup {{ .Chart.Name }}-{{ .Values.web.authorizationService.meta.name }}; do echo 'Waiting for Authorization...'; sleep 2; done" ]

        - name: "{{ .Chart.Name }}-init-configuration"
          image: "{{ .Values.web.initialization.image.name }}:{{ .Values.web.initialization.image.tag }}"
          command: [ "sh", "-c", "until nslookup {{ .Chart.Name }}-{{ .Values.web.configurationService.meta.name }}; do echo 'Waiting for Configuration...'; sleep 2; done" ]
      
      ###########################################
      # Volumes Associated with this Deployment #
      ###########################################

      volumes:
        - name: logs
          emptyDir:
            sizeLimit: 10G
        - name: "{{ .Chart.Name }}-{{ .Values.web.volumes.certificates.name }}"
          secret:
            {{ if not .Values.web.certificates.externalSecret.enabled }}
            secretName: "{{ .Chart.Name }}-{{ .Values.web.certificatesSecret.meta.name }}"
            {{ else }}
            secretName: {{ .Values.web.certificates.exernalSecret.name }}
            {{ end }}
            optional: false
