####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Service

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Values.mysqlService.meta.name }}"
  labels:
    application: "{{ .Values.mysqlService.meta.name }}"

##################################
# Complete Service Specification #
##################################

spec:

  ###############################
  # Pod Selection Configuration #
  ###############################

  selector:
    application: "{{ .Values.mysqlService.meta.name }}"

  ##############################
  # Service Port Configuration #
  ##############################

  ports:

    - name: mysql
      port: {{ .Values.mysqlService.ports.mysql }}
      targetPort: 3306
