####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: ConfigMap

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-{{ .Values.web.rabbitmqMap.meta.name }}"
  labels:
    application: "{{ .Chart.Name }}-{{ .Values.web.rabbitmqMap.meta.name }}"

##########################
# Configuration Map Data #
##########################

data: 

  #########################################
  # RabbitMQ Enabled Plugin Configuration #
  #########################################

  enabled_plugins: |
    [rabbitmq_management].
  
  ##################################
  # RabbitMQ General Configuration #
  ##################################

  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_consul
    # do compute service address
    cluster_formation.consul.svc_addr_auto = true
    # compute service address using node name
    cluster_formation.consul.svc_addr_use_nodename = true
    # health check interval (node TTL) in seconds
    cluster_formation.consul.svc_ttl = 30
    # how soon should nodes that fail their health checks be unregistered by Consul?
    # this value is in seconds and must not be lower than 60 (a Consul requirement)
    cluster_formation.consul.deregister_after = 90
    cluster_partition_handling = autoheal
    # Enable the guest user
    loopback_users.guest = false
