####################################
# Core Helm Template Configuration #
####################################
{{- if .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Chart.Name }}-web-ingress"
  annotations:
    {{- with .Values.web.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

####################################
# Ingress Controller Specification #
####################################

spec:

  ################################################
  # Transport-Layer Security (TLS) Configuration #
  ################################################


  #########################################
  # Ingress Controller Rule Configuration #
  #########################################
  ingressClassName: "{{ .Values.web.ingress.services.ingressClassName }}"
  rules:
    - host: "{{ .Values.web.ingress.webservice.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Chart.Name }}-{{ .Values.web.datawaveService.meta.name }}"
                port: 
                  number: {{ .Values.web.datawaveService.ports.https }}
{{- end }}
