{{- $replicaCount := int .Values.zookeeper.replicaCount }}
{{- if and .Values.zookeeper.pdb.create (gt $replicaCount 1) }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ template "zookeeper.namespace" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
    {{- if .Values.zookeeper.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.zookeeper.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.zookeeper.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.zookeeper.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.zookeeper.pdb.minAvailable }}
  minAvailable: {{ .Values.zookeeper.pdb.minAvailable }}
  {{- end  }}
  {{- if .Values.zookeeper.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.zookeeper.pdb.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: zookeeper
{{- end }}
