{{- if and .Values.zookeeper.metrics.enabled .Values.zookeeper.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.names.fullname" . }}
  {{- if .Values.zookeeper.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.zookeeper.metrics.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- if .Values.zookeeper.metrics.serviceMonitor.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.zookeeper.metrics.serviceMonitor.additionalLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.zookeeper.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.zookeeper.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.zookeeper.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.zookeeper.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.zookeeper.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.zookeeper.metrics.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      {{- if .Values.zookeeper.metrics.serviceMonitor.selector }}
      {{- include "common.tplvalues.render" (dict "value" .Values.zookeeper.metrics.serviceMonitor.selector "context" $) | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: tcp-metrics
      path: "/metrics"
      {{- if .Values.zookeeper.metrics.serviceMonitor.interval }}
      interval: {{ .Values.zookeeper.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.zookeeper.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.zookeeper.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.zookeeper.metrics.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.zookeeper.metrics.serviceMonitor.relabelings "context" $) | nindent 6 }}
      {{- end }}
      {{- if .Values.zookeeper.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.zookeeper.metrics.serviceMonitor.metricRelabelings "context" $) | nindent 6 }}
      {{- end }}
      {{- if .Values.zookeeper.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.zookeeper.metrics.serviceMonitor.honorLabels }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ template "zookeeper.namespace" . }}
{{- end }}
