global:
  security:
    userid: 1000
  dockerRegistry:
    url: ghcr.io/nationalsecurityagency
  volumes:
    certificates:
      name: certificates
      destination: /data/certs
  initialization:
    image:
      name: busybox
      tag: 1.28
  certSecretName: certificates-secret
  pullSecrets:
    - dockerconfigjson-ghcr
  serviceDns:
    configuration:
      name: configuration
      port: 8888
    authorization:
      name: authorization
      port: 8080
    cache:
      name: cache
      port: 8080


#######################################
# Default Values for Audit Deployment #
#######################################
image:
  name: datawave-query-executor-service
  pullPolicy: IfNotPresent
  tag: latest
args:
- "--spring.output.ansi.enabled=ALWAYS"
- "--spring.profiles.active= default,k8s,remoteauth,querymessaging,metricssource,federation,query,pool1"
livenessProbe:
  delaySeconds: 20
  periodSeconds: 5
  failureThreshold: 60
  port: 8080
  scheme: HTTP
  uri: executor/mgmt/health
meta:
  name: executor
service:
  name: executor
readinessProbe:
  delaySeconds: 20
  periodSeconds: 5
  failureThreshold: 60
  port: 8080
  scheme: HTTP
  uri: executor/mgmt/health
replication:
  maxSurge: 2
  maxUnavailable: 1
  replicaCount: 1
  revisionHistoryLimit: 10
restartPolicy: Always
  
#######################################
# Default Values for Executor Service #
#######################################

ports:
  http: 8080
  https: 8443
