global:
  security:
    userid: 1000
    fsgroupid: 1000
  dockerRegistry:
    url: ghcr.io/nationalsecurityagency
  volumes:
    certificates:
      name: certificates
      destination: /data/certs
  initialization:
    image:
      name: busybox
      tag: 1.28
  certSecretName: certificates-secret
  pullSecrets:
    - dockerconfigjson-ghcr
  serviceDns:
    kafka:
      name: kafka
      port: 9092

#######################################
# Default Values for Audit Deployment #
#######################################
image:
  name: obsidiandynamics/kafdrop
  pullPolicy: IfNotPresent
  tag: latest
args: []

meta:
  name: kafdrop
service:
  name: kafdrop

replication:
  maxSurge: 2
  maxUnavailable: 1
  replicaCount: 1
  revisionHistoryLimit: 10
restartPolicy: Always
  
#######################################
# Default Values for Executor Service #
#######################################

ports:
  kafdrop: 9000
