global:
  pullSecrets: 
  - dockerconfigjson-ghcr
init:
  image:
    name: ghcr.io/nationalsecurityagency/datawave-community-operator
    tag: 8.4
clusters:
  - name: mysql-cluster
    serviceName: mysql-cluster
    secretName: mysql-secret
    tlsUseSelfSigned: true
    instances: 3
    router:
      instances: 1
    backup:
      enabled: false
      name: myBackup
      excludeTables: []
      claimName: backup-pvc
      schedule:
        name: nightly
        cron: "0 1 * * *"
        enabled: true
    databaseUsers:
    - name: datawave
      secretName: mysql-secret
      secretKeyRef: rootPassword
      databases:
      - example
    # Optional init script content. If specified, this will be used directly.
    initScript: |
      create database example;
      use example;
      GRANT ALL PRIVILEGES ON example TO 'datawave'@'%' WITH GRANT OPTION;