{{- if and (ne .Values.namespace "default") (.Values.createNamespace) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    {{- include "metrics.labels" . | nindent 4 }}
{{- end }}

