apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics.prometheusServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type | default "ClusterIP" }}
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.prometheus.service.type "NodePort") .Values.prometheus.service.nodePort }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
      {{- end }}
  selector:
    {{- include "metrics.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus

