{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metrics.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "metrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}

