#####################################
# DataWave Helm Chart Configuration #
#####################################

apiVersion: v2
name: datawave-system
type: application
version: 1.0.0

#################################
# Basic Metadata for this Chart #
#################################

appVersion: 1.0.0
description: Deploys an Entire DataWave Stack w/ Dependencies
icon: https://code.nsa.gov/datawave/images/datawave-logo.png



dependencies:
  - name: dwv-ingest
    repository: file://../ingest
    version: 1.0.0
  - name: dwv-hadoop
    repository: file://../hadoop
    version: 1.0.0
  - name: dwv-zookeeper
    repository: file://../zookeeper
    version: 1.0.0
  - name: dwv-accumulo
    repository: file://../accumulo
    version: 1.0.0
  - name: datawave-monolith-umbrella
    repository: file://../datawave-monolith-umbrella
    version: 1.0.0
