#####################################
# DataWave Helm Chart Configuration #
#####################################

apiVersion: v2
name: datawave-system
type: application
version: 1.0.2-SNAPSHOT

#################################
# Basic Metadata for this Chart #
#################################

appVersion: 1.0.0
description: Deploys an Entire DataWave Stack w/ Dependencies
icon: https://code.nsa.gov/datawave/images/datawave-logo.png

dependencies:
  - name: dwv-ingest
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.1
    path: ../ingest
  - name: dwv-hadoop
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../hadoop
    condition: charts.hadoop.enabled
  - name: dwv-hadoop-config
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../hadoop-config
  - name: dwv-zookeeper
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../zookeeper
    condition: charts.zookeeper.enabled
  - name: dwv-accumulo
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../accumulo
  - name: datawave-monolith-umbrella
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0
    path: ../datawave-monolith-umbrella
  - name: dwv-executor
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0-SNAPSHOT
    path: ../executor
    condition: charts.qms.enabled
  - name: dwv-kafdrop
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0-SNAPSHOT
    path: ../kafdrop
    condition: charts.qms.enabled
  - name: dwv-kafka
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0-SNAPSHOT
    path: ../kafka
    condition: charts.qms.enabled
  - name: dwv-modification
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0-SNAPSHOT
    path: ../modification
    condition: charts.qms.enabled
  - name: dwv-mr-query
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0-SNAPSHOT
    path: ../mr-query
    condition: charts.qms.enabled
  - name: dwv-query-metrics
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0-SNAPSHOT
    path: ../query-metrics
    condition: charts.qms.enabled
  - name: dwv-query
    repository: oci://ghcr.io/nationalsecurityagency/datawave-helm-charts/charts
    version: 1.0.0-SNAPSHOT
    path: ../query
    condition: charts.qms.enabled
