#####################################
# DataWave Helm Chart Configuration #
#####################################

apiVersion: v2
name: datawave-system
type: application
version: 3.40.0

#################################
# Basic Metadata for this Chart #
#################################

appVersion: 3.40.0
description: Deploys an Entire DataWave Stack w/ Dependencies
home: https://gitlab.evoforge.org/datawave/cloud_deploy/datawave_query/helm
icon: https://code.nsa.gov/datawave/images/datawave-logo.png



dependencies:
  - name: dwv-ingest
    repository: file://../ingest
    version: 3.38.1
  - name: dwv-web
    repository: file://../web
    version: 3.40.0
  - name: dwv-zookeeper
    repository: file://../zookeeper
    version: 3.6.3
  - name: dwv-accumulo
    repository: file://../accumulo
    version: 2.1.0
  - name: dwv-hadoop
    repository: file://../hadoop
    version: 3.3.3
