dwv-accumulo:
  image:
    tag: 2.1.4-dwv-f297977
  initContainer:
    tag: 3.3.6
dwv-hadoop:
  image:
    repository: containeryard.evoforge.org/warehouses/datawave-stack-hadoop
    tag: 3.4.1
dwv-ingest:
  image:
    tag: 7.18.0-lpj
    
