######################################
# Default Values for Docker Registry #
######################################
global:
  dockerRegistry:
    url: ""
charts:
  zookeeper:
    enabled: true
  hadoop:
    enabled: true
external:
  zookeeper:
    hosts:
      - zookeeper
  hdfs:
    hosts:
      - hdfs-nn
      - hdfs-dn
  yarn:
    hosts:
      - yarn-rm
      - yarn-nm

datawave-monolith-umbrella:
  dwv-annotation-cache:
    image:
      name: nationalsecurityagency/datawave/annotation-cache-service
      tag: 1.0.0-SNAPSHOT
    args:
      - "--spring.profiles.active=default,k8s,rest,region-local,rabbit-confirms"
  sonicweb:
    image:
      name: nationalsecurityagency/datawave/sonicweb-service
      tag: 1.4.0-SNAPSHOT
    args:
      - "--spring.profiles.active=default,k8s,remoteauth,region-local,hazelcast-cache"
  dwv-audit:
    args:
      - "--spring.output.ansi.enabled=ALWAYS"
      - "--spring.profiles.active=default,k8s,logs,rabbit-confirms"

dwv-hadoop:
  persistence:
    nameNode:
      enabled: true
      definitions:
        - metadata:
            name: dfs
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-hostpath-sc"
            resources:
              requests:
                storage: 5Gi
            selector:
    dataNode:
      enabled: true
      definitions:
        - metadata:
            name: dfs
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-hostpath-sc"
            resources:
              requests:
                storage: 5Gi
            selector:
dwv-zookeeper:
  persistence:
    enabled: true