####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Service

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Values.datawaveService.meta.name }}-http"
  labels:
    application: "{{ .Values.datawaveService.meta.name }}"

##################################
# Complete Service Specification #
##################################

spec:

  ###############################
  # Pod Selection Configuration #
  ###############################

  selector:
    application: "{{ .Values.datawaveDeployment.meta.name }}"

  ##############################
  # Service Port Configuration #
  ##############################

  ports:

    - name: http
      port: {{ .Values.datawaveService.ports.http }}
      targetPort: 8080