# Required
input:
  - values.yaml

draft: 2020
indent: 4
output: values.schema.json

schemaRoot:
  id: https://code.nsa.org/datawave/schema
  title: Helm Values Schema
  description: Schema for DataWave Helm values
  additionalProperties: true
