hazelcast:
  client:
    k8s:
      service-dns-name: {{ .Chart.Name }}-{{ .Values.web.cacheService.meta.name }}.{{ .Release.Namespace }}.svc.cluster.local



      # This template is for configuring your site-specific properties for all microservices.
system.name: CONTAINERS


# Define the client certificates (in lower-case subjectDN<issuerDN> form) that are allowed to call a service. Note that you only need to
# specify one value in the list below.
# Since enforce-allowed-callers is false, you can skip configuring this section if you want.
spring:
  security:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      autoOffsetReset: earliest
      enableAutoCommit: false
      properties:
        allow.auto.create.topics: false

# This is the accumulo configuration we use in services.  These don't map directly to a properties class, but 
# they are here to be used as a reference for other properties.
accumulo:
  zookeepers: '{{ .Values.web.zookeeper.quorom }}'
  instanceName: '{{ .Values.web.accumulo.instanceName }}'
  username: '{{ .Values.web.accumulo.user }}'
  password: '{{ .Values.web.accumulo.password }}'
# Configuration placeholders which 1) determines what backend will be used for transmitting query results
# and 2) determines the message size limit before claim checks are used with RabbitMQ messaging
messaging:
  backend: ${BACKEND:kafka}
  maxMessageSizeBytes: 536870912
