{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: "{{ .Values.ingress.annotation.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.meta.name }}"
                port:
                  number: {{ .Values.ports.https }}
{{- end }}
