---
name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  build-services:
    name: Lint
    runs-on: helm-runner

    permissions: write-all

    strategy:
      matrix:
        chart: [accumulo, audit, authorization, cache, configuration, datawave-monolith, dictionary, hadoop, ingest, mysql, rabbitmq, zookeeper]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: "Package chart"
        run: |
          cd ${{ strategy.matrix.chart }}
          /usr/local/bin/helm package .
        