---
name: Release Chart
    
on:
  push:
  workflow_dispatch:
    inputs:
      RELEASE_CHART_NAME:
        required: true
        description: "Folder name of chart to release."
    
env:
  RELEASE_CHART_NAME: ${{ github.event.inputs.RELEASE_CHART_NAME || 'common-service-library' }}

jobs:
  release-chart:
    runs-on: ubuntu-latest

    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      run: |
        cd ${{ env.RELEASE_CHART_NAME }}
        sed -i -E 's/^(version:.*)-SNAPSHOT$/\1/' Chart.yaml
    - name: Get Version
      run: |
        cat Chart.yaml | grep version: | awk '{print "${{ env.RELEASE_CHART_NAME }}-"$NF}''

