---
name: Release Chart
    
on:
  push:
  workflow_dispatch:
    inputs:
      RELEASE_CHART_NAME:
        required: true
        description: "Folder name of chart to release."
    
env:
  RELEASE_CHART_NAME: ${{ github.event.inputs.RELEASE_CHART_NAME || 'common-service-library' }}

jobs:
  release-chart:
    runs-on: ubuntu-latest

    permissions: write-all
    steps:
    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/${{ env.RELEASE_CHART_NAME }}
        sed -i.bak -E 's/^(version:.*)-SNAPSHOT$/\1/' "$FILE"
        cat Chart.yml
