---
name: Release Chart
    
on:
  workflow_dispatch:
    inputs:
      RELEASE_CHART_NAME:
        required: true
        description: "Folder name of chart to release."
      TAG_NAME:
        required: true
        description: "Tag to Release."
    
env:
  RELEASE_CHART_NAME: ${{ github.event.inputs.RELEASE_CHART_NAME || 'common-service-library' }}


jobs:
  release-chart:
    runs-on: self-hosted

    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set environment variables
      id: set-variables
      run: |
          echo "VERSION=$(yq -r .version ${{ env.RELEASE_CHART_NAME}}/Chart.yaml)" >> "$GITHUB_OUTPUT"          

    - name: Env variable output
      id: test-variables
      run: |
          echo ${{ steps.set-variables.outputs.VERSION }}          


    - name: Package and push helm chart
      run: |
        source /secrets/helm-secrets
        helm repo add self-hosted-repo ${HELM_REPO_URL} --username ${HELM_REPO_USER} --password ${HELM_REPO_PASSWORD}
        
        git checkout ${{ env.TAG_NAME}}

        cd ${{ env.RELEASE_CHART_NAME}}
        export CHART_NAME=$(cat Chart.yaml | grep "^name:" | awk '{print $NF}' )
        helm package . --version ${{ steps.set-variables.outputs.VERSION }} --dependency-update
        helm push ${CHART_NAME}-${{ steps.set-variables.outputs.VERSION }}.tgz self-hosted-repo