global:
  dockerRegistry:
    url: ghcr.io/nationalsecurityagency
  volumes:
    certificates:
      name: certificates
      destination: /data/certs
  initialization:
    image:
      name: busybox
      tag: 1.28
  certSecretName: certificates-secret
  pullSecrets:
    - dockerconfigjson-ghcr
  serviceDns:
    configuration:
      name: configuration
      port: 8888
    authorization:
      name: authorization
      port: 8080
    cache:
      name: cache
      port: 8080


#######################################
# Default Values for Audit Deployment #
#######################################
image:
<<<<<<< HEAD
  name: datawave-query-metric-service
  pullPolicy: Always
  tag: latest
=======
  name: datawave-mapreduce-query-service
  pullPolicy: IfNotPresent
  tag: 4.0.8
>>>>>>> 356f4da (QMS next step complete)
args:
- "--spring.output.ansi.enabled=ALWAYS"
- "--spring.profiles.active=default,k8s,remoteauth"
livenessProbe:
  delaySeconds: 20
  periodSeconds: 5
  failureThreshold: 60
  port: 8080
  scheme: HTTP
  uri: querymetric/mgmt/health
meta:
  name: querymetric
service:
  name: querymetric
readinessProbe:
  delaySeconds: 20
  periodSeconds: 5
  failureThreshold: 60
  port: 8080
  scheme: HTTP
  uri: querymetric/mgmt/health
replication:
  maxSurge: 2
  maxUnavailable: 1
  replicaCount: 1
  revisionHistoryLimit: 10
restartPolicy: Always
  
#######################################
# Default Values for Executor Service #
#######################################

ports:
  http: 8080
  https: 8443
